service:
    name: guineapigapp2_hsvc
    identifier: guineapigapp2_hsvc
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                    identifier: guineapigapp2_hsvc
                    type: K8sManifest
                    spec:
                      store:
                        type: Github
                        spec:
                            connectorRef: harnessgitconnector
                            gitFetchType: Branch
                            paths:
                                - guineapigapp2/guineapigapp2-ui-deployment.yaml
                                - guineapigapp2/guineapigapp2-ui-svc.yaml
                            repoName: harnesscd-example-apps
                            branch: master
                        skipResourceVersioning: false
                        enableDeclarativeRollback: false
    gitOpsEnabled: false
